# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'ubuntu-latest'

trigger:
- master

steps:
- task: NodeTool@0
  displayName: 'Install Node 10.9.0'
  inputs:
    versionSpec: '10.9.0'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: ./
    verbose: false

- task: Npm@1
  displayName: 'npm run lint'
  inputs:
    command: custom
    workingDir: ./
    verbose: false
    customCommand: 'run lint'

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    workingDir: ./
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'npm test:ci'
  inputs:
    command: custom
    workingDir: ./
    verbose: false
    customCommand: 'run test:ci'

- task: PublishTestResults@2
  displayName: 'Publish Test Results test-results.xml'
  inputs:
    testResultsFiles: './test-results.xml'
    testRunTitle: 'Test results'
